version: '3.1'

services:
  db:
    image: mysql:9.0.1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: development-root
      MYSQL_DATABASE: fans-crm
      MYSQL_USER: fans-crm
      MYSQL_PASSWORD: development
  app:
    image: oeoen/fans-crm-assesment-backend:0.0.1
    environment:
      MYSQL_HOST: db
      MYSQL_ROOT_PASSWORD: development-root
      MYSQL_DATABASE: fans-crm
      MYSQL_USER: fans-crm
      MYSQL_PASSWORD: development
    ports:
      - '3000:3000'
    depends_on:
      - db
